// This database contains the real product matrix with all pricing components

export interface ProductoMatriz {
  id: string
  material: string // PVC, ALUMINIO_A, ALUMINIO_B
  tipo: string // CORREADERA_GRANDE, CORREADERA_CHICA, FIJO, PROYECTANTE, PUERTA, ELEMENTO_ESPECIAL
  anchoM: number // Ancho en metros
  altoM: number // Alto en metros
  costoColoradoBase: number // Costo base colorado
  datoIntermedio: number // Interpolación de valor
  termosMts: number // Metros cuadrados (calculado: ancho × alto)
  m2Termos: number // Precio por m2 de termos
  perfil: number // Costo de perfil
  herraje: number // Costo de herraje
  margenPorcentaje: number // % de margen
}

// Matriz de productos basada en la imagen proporcionada
export const MATRIZ_PRODUCTOS: ProductoMatriz[] = [
  // CORREADERA GRANDE - BLANCO
  {
    id: "correadera-grande-3500-2200",
    material: "PVC",
    tipo: "CORREADERA_GRANDE",
    anchoM: 3.5,
    altoM: 2.2,
    costoColoradoBase: 350000,
    datoIntermedio: 350000,
    termosMts: 7.7,
    m2Termos: 46.784,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "correadera-grande-3000-2200",
    material: "PVC",
    tipo: "CORREADERA_GRANDE",
    anchoM: 3.0,
    altoM: 2.2,
    costoColoradoBase: 320000,
    datoIntermedio: 320000,
    termosMts: 6.6,
    m2Termos: 46.784,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "correadera-grande-2320-2200",
    material: "PVC",
    tipo: "CORREADERA_GRANDE",
    anchoM: 2.32,
    altoM: 2.2,
    costoColoradoBase: 252644,
    datoIntermedio: 252644,
    termosMts: 5.104,
    m2Termos: 46.784,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "correadera-grande-2200-2200",
    material: "PVC",
    tipo: "CORREADERA_GRANDE",
    anchoM: 2.2,
    altoM: 2.2,
    costoColoradoBase: 240000,
    datoIntermedio: 240000,
    termosMts: 4.84,
    m2Termos: 46.784,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "correadera-grande-1750-2000",
    material: "PVC",
    tipo: "CORREADERA_GRANDE",
    anchoM: 1.75,
    altoM: 2.0,
    costoColoradoBase: 200000,
    datoIntermedio: 200000,
    termosMts: 3.5,
    m2Termos: 54.7,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "correadera-grande-1500-2000",
    material: "PVC",
    tipo: "CORREADERA_GRANDE",
    anchoM: 1.5,
    altoM: 2.0,
    costoColoradoBase: 150000,
    datoIntermedio: 150000,
    termosMts: 3.0,
    m2Termos: 46.784,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },

  // CORREADERA CHICA - BLANCO
  {
    id: "correadera-chica-3000-1600",
    material: "PVC",
    tipo: "CORREADERA_CHICA",
    anchoM: 3.0,
    altoM: 1.6,
    costoColoradoBase: 139974,
    datoIntermedio: 139974,
    termosMts: 4.8,
    m2Termos: 35.25,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "correadera-chica-2500-1500",
    material: "PVC",
    tipo: "CORREADERA_CHICA",
    anchoM: 2.5,
    altoM: 1.5,
    costoColoradoBase: 139974,
    datoIntermedio: 139974,
    termosMts: 3.75,
    m2Termos: 35.25,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "correadera-chica-1600-1500",
    material: "PVC",
    tipo: "CORREADERA_CHICA",
    anchoM: 1.6,
    altoM: 1.5,
    costoColoradoBase: 99546,
    datoIntermedio: 99546,
    termosMts: 2.4,
    m2Termos: 35.807,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "correadera-chica-1400-1425",
    material: "PVC",
    tipo: "CORREADERA_CHICA",
    anchoM: 1.4,
    altoM: 1.425,
    costoColoradoBase: 92000,
    datoIntermedio: 92000,
    termosMts: 1.995,
    m2Termos: 35.807,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "correadera-chica-1200-1200",
    material: "PVC",
    tipo: "CORREADERA_CHICA",
    anchoM: 1.2,
    altoM: 1.2,
    costoColoradoBase: 72000,
    datoIntermedio: 72000,
    termosMts: 1.44,
    m2Termos: 35.807,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "correadera-chica-1000-1000",
    material: "PVC",
    tipo: "CORREADERA_CHICA",
    anchoM: 1.0,
    altoM: 1.0,
    costoColoradoBase: 60000,
    datoIntermedio: 60000,
    termosMts: 1.0,
    m2Termos: 35.807,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },

  // FIJO - BLANCO
  {
    id: "fijo-1600-2200",
    material: "PVC",
    tipo: "FIJO",
    anchoM: 1.6,
    altoM: 2.2,
    costoColoradoBase: 33351,
    datoIntermedio: 33351,
    termosMts: 3.52,
    m2Termos: 35.807,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "fijo-1500-1500",
    material: "PVC",
    tipo: "FIJO",
    anchoM: 1.5,
    altoM: 1.5,
    costoColoradoBase: 33351,
    datoIntermedio: 33351,
    termosMts: 2.25,
    m2Termos: 35.807,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "fijo-1200-1500",
    material: "PVC",
    tipo: "FIJO",
    anchoM: 1.2,
    altoM: 1.5,
    costoColoradoBase: 33351,
    datoIntermedio: 33351,
    termosMts: 1.8,
    m2Termos: 35.807,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "fijo-1200-1300",
    material: "PVC",
    tipo: "FIJO",
    anchoM: 1.2,
    altoM: 1.3,
    costoColoradoBase: 33351,
    datoIntermedio: 33351,
    termosMts: 1.56,
    m2Termos: 35.807,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "fijo-1000-1000",
    material: "PVC",
    tipo: "FIJO",
    anchoM: 1.0,
    altoM: 1.0,
    costoColoradoBase: 33351,
    datoIntermedio: 33351,
    termosMts: 1.0,
    m2Termos: 35.807,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "fijo-800-800",
    material: "PVC",
    tipo: "FIJO",
    anchoM: 0.8,
    altoM: 0.8,
    costoColoradoBase: 33351,
    datoIntermedio: 33351,
    termosMts: 0.64,
    m2Termos: 35.807,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },

  // PROYECTANTE - BLANCO
  {
    id: "proyectante-1100-1100",
    material: "PVC",
    tipo: "PROYECTANTE",
    anchoM: 1.1,
    altoM: 1.1,
    costoColoradoBase: 66066,
    datoIntermedio: 66066,
    termosMts: 1.21,
    m2Termos: 22.516,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "proyectante-1100-950",
    material: "PVC",
    tipo: "PROYECTANTE",
    anchoM: 1.1,
    altoM: 0.95,
    costoColoradoBase: 66066,
    datoIntermedio: 66066,
    termosMts: 1.045,
    m2Termos: 16.614,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "proyectante-700-950",
    material: "PVC",
    tipo: "PROYECTANTE",
    anchoM: 0.7,
    altoM: 0.95,
    costoColoradoBase: 66066,
    datoIntermedio: 66066,
    termosMts: 0.665,
    m2Termos: 16.614,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "proyectante-600-600",
    material: "PVC",
    tipo: "PROYECTANTE",
    anchoM: 0.6,
    altoM: 0.6,
    costoColoradoBase: 66066,
    datoIntermedio: 66066,
    termosMts: 0.36,
    m2Termos: 22.516,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "proyectante-400-600",
    material: "PVC",
    tipo: "PROYECTANTE",
    anchoM: 0.4,
    altoM: 0.6,
    costoColoradoBase: 66066,
    datoIntermedio: 66066,
    termosMts: 0.24,
    m2Termos: 22.516,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "proyectante-300-300",
    material: "PVC",
    tipo: "PROYECTANTE",
    anchoM: 0.3,
    altoM: 0.3,
    costoColoradoBase: 66066,
    datoIntermedio: 66066,
    termosMts: 0.09,
    m2Termos: 22.516,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },

  // PUERTA - BLANCO
  {
    id: "puerta-900-2200",
    material: "PVC",
    tipo: "PUERTA",
    anchoM: 0.9,
    altoM: 2.2,
    costoColoradoBase: 138135,
    datoIntermedio: 138135,
    termosMts: 1.98,
    m2Termos: 105.728,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
  {
    id: "puerta-doble-1800-2300",
    material: "PVC",
    tipo: "PUERTA",
    anchoM: 1.8,
    altoM: 2.3,
    costoColoradoBase: 138135,
    datoIntermedio: 138135,
    termosMts: 4.14,
    m2Termos: 105.728,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },

  // ELEMENTO ESPECIAL - BLANCO
  {
    id: "elemento-especial",
    material: "PVC",
    tipo: "ELEMENTO_ESPECIAL",
    anchoM: 0,
    altoM: 0,
    costoColoradoBase: 138135,
    datoIntermedio: 138135,
    termosMts: 0,
    m2Termos: 105.728,
    perfil: 0,
    herraje: 0,
    margenPorcentaje: 83,
  },
]

// Función para encontrar el producto más cercano por medidas
export function encontrarProductoCercano(
  material: string,
  tipo: string,
  anchoM: number,
  altoM: number,
): ProductoMatriz | null {
  const productos = MATRIZ_PRODUCTOS.filter((p) => p.material === material && p.tipo === tipo)

  if (productos.length === 0) return null

  // Si hay exactamente una coincidencia, devolverla
  if (productos.length === 1) return productos[0]

  // Encontrar el producto más cercano por medidas
  return productos.reduce((closest, current) => {
    const diffActual = Math.abs(closest.anchoM - anchoM) + Math.abs(closest.altoM - altoM)
    const diffCurrent = Math.abs(current.anchoM - anchoM) + Math.abs(current.altoM - altoM)
    return diffCurrent < diffActual ? current : closest
  })
}

// Función para interpolar linealmente el costo
export function interpolarCosto(
  producto1: ProductoMatriz,
  producto2: ProductoMatriz,
  medidaTarget: number,
  medidaRef1: number,
  medidaRef2: number,
): number {
  const porcentaje = (medidaTarget - medidaRef1) / (medidaRef2 - medidaRef1)
  return Math.round(
    producto1.costoColoradoBase + (producto2.costoColoradoBase - producto1.costoColoradoBase) * porcentaje,
  )
}
